name: o11y
recipe: lamp
config:
  webroot: web

proxy:
  alloy:
    - alloy.o11y.lndo.site:12345
  grafana:
    - grafana.o11y.lndo.site:3000
  graphite:
    - graphite.o11y.lndo.site:80
  loki:
    - loki.o11y.lndo.site:3100
  mimir:
    - mimir.o11y.lndo.site:8080

variables:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.o11y.internal:4318

services:
  appserver:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmnl0
    config:
      vhosts: config/example/apache2/default.conf
    run_as_root:
      - collectd
    overrides:
      volumes:
        - ./config/example/apache2/status.conf:/etc/apache2/conf-enabled/status.conf
        - ./config/example/collectd/collectd.conf.d/common.conf:/etc/collectd/collectd.conf.d/10-common.conf
        - ./config/example/collectd/collectd.conf.d/appserver.conf:/etc/collectd/collectd.conf.d/20-appserver.conf
        - apache_logs_data:/var/log/apache2

  database:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmariadb-dev libmnl0
    overrides:
      volumes:
        - ./config/example/collectd/collectd.conf.d/common.conf:/etc/collectd/collectd.conf.d/10-common.conf
        - ./config/example/collectd/collectd.conf.d/database.conf:/etc/collectd/collectd.conf.d/20-database.conf

  alloy:
    type: lando
    api: 3
    services:
      image: grafana/alloy:latest
      command: /bin/alloy run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data --stability.level=experimental /etc/alloy
      ports:
        - '12345'
        - '4317'
        - '4318'
        - '9411'
        - '14268'
    overrides:
      volumes:
        - ./config/alloy/config.alloy:/etc/alloy/config.alloy
        # Make appserver logs available to Alloy.
        - apache_logs_data:/var/log/apache2

  grafana:
    type: lando
    api: 3
    services:
      image: grafana/grafana-enterprise:latest
      command: /run.sh
      ports:
        - '3000'
      volumes:
        - ./config/grafana/provisioning:/etc/grafana/provisioning
        - ./config/grafana/dashboards:/etc/grafana/dashboards
    portforward: true

  graphite:
    type: lando
    api: 3
    services:
      user: root
      image: graphiteapp/graphite-statsd
      command: /entrypoint
      ports:
        - '80'
        - '2003'
    portforward: true
    # @TODO: Persist Graphite data.
    # volumes:
    #   - graphite_data:/opt/graphite/storage

  # Port: 3100, 9096
  loki:
    type: lando
    api: 3
    portforward: true
    services:
      user: root
      image: grafana/loki:latest
      ports:
        - '3100'
        - '9096'
      volumes:
        - ./config/loki/loki.yaml:/etc/loki/local-config.yaml
        - data_loki:/data
        # Make appserver logs available to Loki.
        - apache_logs_data:/var/log/apache2
    overrides:
      entrypoint:
        - '/usr/bin/loki'
        - '-config.file=/etc/loki/local-config.yaml'

  # Port: 9009
  # Volumes: /data/blocks, /data/tsdb, /data/rules
  mimir:
    api: 3
    type: lando
    ports:
      - '9009'
    portforward: true
    services:
      image: grafana/mimir:latest
      command: '/busybox/busybox sh'
      volumes:
        - ./config/mimir/mimir.yaml:/etc/mimir.yaml
    overrides:
      entrypoint:
        - /bin/mimir
        - config.file=/etc/mimir.yaml

  # Generate test OTel data.
  # Usage:
  # - telemetrygen traces --otlp-endpoint alloy.o11y.internal:4317 --otlp-insecure --duration 5s
  telemetrygen:
    type: go
    overrides:
      image: golang:latest
    build:
      - go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest

  # Ports 3200, 9095
  # Ports 4317 and 4318 are alloy, which may relay things to tempo.
  # https://github.com/grafana/tempo/blob/main/example/docker-compose/local/docker-compose.yaml
  # Grafana source: http://tempo.o11y.internal:3200
  tempo:
    type: lando
    api: 3
    services:
      image: grafana/tempo:latest
      command: '/busybox/busybox sh'
      user: root
      ports:
        - "3200"  # tempo
        - "9095"  # tempo grpc
        - "4317"  # otlp grpc
        - "4318"  # otlp http
    scanner:
      disabled: true
    overrides:
      entrypoint:
        - '/tempo'
        - '-config.file=/etc/tempo.yaml'
      volumes:
        - ./config/tempo/tempo.yaml:/etc/tempo.yaml
        - tempo_data:/data

volumes:
  grafana_data: {}
  graphite_data: {}
  loki_data: {}
  mimir_data: {}
  tempo_data: {}
  apache_logs_data: {}
