name: test
recipe: lamp
config:
  webroot: web

proxy:
  grafana:
    - grafana.test.lndo.site:3000
  graphite:
    - graphite.test.lndo.site:80


services:
  appserver:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmnl0
    config:
      vhosts: config/apache2/default.conf
    run_as_root:
      - collectd
    overrides:
      volumes:
        - ./config/collectd/apache.conf:/etc/collectd/collectd.conf.d/apache.conf
        - ./config/collectd/client.conf:/etc/collectd/collectd.conf.d/client.conf
        - ./config/collectd/debug.conf:/etc/collectd/collectd.conf.d/debug.conf
        - ./config/collectd/mysql.conf:/etc/collectd/collectd.conf.d/mysql.conf
        - ./config/collectd/os.conf:/etc/collectd/collectd.conf.d/os.conf
        - ./config/apache2/logformat.conf:/etc/apache2/conf-enabled/logformat.conf
        - ./config/apache2/status.conf:/etc/apache2/conf-enabled/status.conf

  grafana:
    type: lando
    api: 3
    services:
      image: grafana/grafana-enterprise:latest
      command: /run.sh
      ports:
        - '3000'
    portforward: true
    # @TODO: Persist Grafana data.
    # volumes:
    #   - grafana_data:/var/lib/grafana

  graphite:
    type: lando
    api: 3
    services:
      user: root
      image: graphiteapp/graphite-statsd
      command: /entrypoint
      ports:
        - '80'
        - '2003'
    portforward: true
    # @TODO: Persist Graphite data.
    # volumes:
    #   - graphite_data:/opt/graphite/storage

volumes:
  grafana_data: {}
  graphite_data: {}
