name: o11y
recipe: lamp
config:
  webroot: web

proxy:
  alloy:
    - alloy.o11y.lndo.site:12345
  grafana:
    - grafana.o11y.lndo.site:3000
  graphite:
    - graphite.o11y.lndo.site:80
  loki:
    - loki.o11y.lndo.site:3100
  mimir:
    - mimir.o11y.lndo.site:9009
  tempo:
    - tempo.o11y.lndo.site:80

variables:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-grafana:4318

services:
  appserver:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmnl0
    config:
      vhosts: config/apache2/default.conf
    run_as_root:
      - collectd
    overrides:
      volumes:
        - ./config/collectd/apache.conf:/etc/collectd/collectd.conf.d/apache.conf
        - ./config/collectd/client.conf:/etc/collectd/collectd.conf.d/client.conf
        - ./config/collectd/debug.conf:/etc/collectd/collectd.conf.d/debug.conf
        - ./config/collectd/mysql.conf:/etc/collectd/collectd.conf.d/mysql.conf
        - ./config/collectd/os.conf:/etc/collectd/collectd.conf.d/os.conf
        - ./config/apache2/logformat.conf:/etc/apache2/conf-enabled/logformat.conf
        - ./config/apache2/status.conf:/etc/apache2/conf-enabled/status.conf

  alloy:
    type: lando
    api: 3
    services:
      image: grafana/alloy:latest
      command: /bin/alloy run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data --stability.level=experimental /etc/alloy
      ports:
        - '12345'
    overrides:
      environment:
        - VIRTUAL_HOST='o11y.lndo.site'
        - HTTP_EXPOSE=12345:12345,4317:4317,4318:4318,9411:9411,14268:14268
        - HTTPS_EXPOSE=12345:12345,4317:4317,4318:4318,9411:9411,14268:14268
      volumes:
        - ./config/alloy/config.alloy:/etc/alloy/config.alloy

  grafana:
    type: lando
    api: 3
    services:
      image: grafana/grafana-enterprise:latest
      command: /run.sh
      ports:
        - '3000'
    portforward: true
    # @TODO: Persist Grafana data.
    # volumes:
    #   - grafana_data:/var/lib/grafana

  graphite:
    type: lando
    api: 3
    services:
      user: root
      image: graphiteapp/graphite-statsd
      command: /entrypoint
      ports:
        - '80'
        - '2003'
    portforward: true
    # @TODO: Persist Graphite data.
    # volumes:
    #   - graphite_data:/opt/graphite/storage

  mimir:
    type: lando
    api: 3
    services:
      user: root
      image: grafana/mimir:latest
      command: /
      ports:
        - '9009'
    portforward: true
    overrides:
      volumes:
        - ./config/mimir:/etc/mimir

  tempo:
    type: lando
    api: 3
    services:
      user: root
      image: grafana/tempo:latest
      command: /entrypoint
      ports:
        - '9009'
    portforward: true
    overrides:
      volumes:
        - ./config/mimir:/etc/mimir
volumes:
  grafana_data: {}
  graphite_data: {}