{
 "title": "Servers - Collectd",
 "description": "CollectD & Graphite Server Metrics Dashboard with CPU, Memory, IO & Disk Stats, Network, NTP, and others. Based on https://grafana.com/grafana/dashboards/24-collectd-server-metrics/",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_PREFIX}" },
   {
    "name": "server",
    "query": {}
   },
   {
    "name": "timeperiod",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Summarises", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(lando.$server.uptime.uptime)"
    }
   ]
  },
  {
   "title": "Load Avg (5m)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(lando.$server.load.load.midterm)"
    }
   ]
  },
  {
   "title": "Max Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sumSeries(summarize(lando.$server.processes.ps_state-zombies, '$timeperiod', 'max', false))"
    }
   ]
  },
  {
   "title": "Proc run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sumSeries(summarize(lando.$server.processes.ps_state-running, '$timeperiod', 'sum', false))"
    }
   ]
  },
  {
   "title": "Proc blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sumSeries(lando.$server.processes.ps_state-blocked)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(sumSeries(keepLastValue(exclude(lando.$server.cpu-*.percent-*, 'idle'), INF)), #B)",
     "targetFull": "asPercent(sumSeries(keepLastValue(exclude(lando.$server.cpu-*.percent-*, 'idle'), INF)), sumSeries(keepLastValue(lando.$server.cpu-*.percent-*, INF)))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "asPercent(sumSeries(keepLastValue(lando.$server.memory.memory-used, INF)), #B)",
     "targetFull": "asPercent(sumSeries(keepLastValue(lando.$server.memory.memory-used, INF)), sumSeries(keepLastValue(lando.$server.memory.memory-*, INF)))"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(sumSeries(keepLastValue(lando.$server.swap.swap-{used,cached}, INF)), #B)",
     "targetFull": "asPercent(sumSeries(keepLastValue(lando.$server.swap.swap-{used,cached}, INF)), sumSeries(keepLastValue(lando.$server.swap.swap-*, INF)))"
    }
   ]
  },
  {
   "title": "Disk Usage (max)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "maxSeries(aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2))",
     "targetFull": "maxSeries(aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(lando.$server.df-*.df_complex-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(lando.$server.df-*.df_complex-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2))"
    }
   ]
  },
  {
   "title": "Disk Inode (max)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "maxSeries(exclude(aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2), 'boot'))",
     "targetFull": "maxSeries(exclude(aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(lando.$server.df-*.df_inodes-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(lando.$server.df-*.df_complex-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2), 'boot'))"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(maxSeries(scale(summarize(lando.$server.disk-*.disk_io_time.io_time, '$timeperiod', 'max'), 0.001)), '.*disk-(\\w+).*', ' \\1')"
    }
   ]
  },
  {
   "title": "Logged users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sumSeries(lando.$server.users.users)"
    }
   ]
  },
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(summarize(groupByNode(exclude(lando.$server.cpu.*.cpu.*, 'idle'), 1, 'sum'), '$timeperiod', 'max', false), 0), '(.*)', '\\1 Total Used')"
    },
    {
     "target": "aliasByNode(summarize(exclude(lando.$server.cpu.*.cpu.*, 'idle'), '$timeperiod', 'max', false), 1, 3)"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(aliasByNode(lando.$server.memory.memory-*, 1, 3)), 1)"
    },
    {
     "target": "aliasByNode(exclude(exclude(lando.$server.memory.memory-*, 'free'), 'cached'), 1, 3)"
    },
    {
     "target": "aliasByNode(lando.$server.memory.memory-free, 1, 3)"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "exclude(aliasByNode(lando.$server.swap.swap-*, 1, 3), 'free')"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(lando.$server.load.load.*, '$timeperiod', 'max', false), 1, 4)"
    },
    {}
   ]
  },
  {
   "title": "Process Fork/sec Max",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(perSecond(lando.$server.processes.fork_rate), '$timeperiod', 'max', false), 1)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(exclude(lando.$server.processes.ps_state-*, 'sleeping'), '$timeperiod', 'max', false), 1, 3)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "target": "aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2)",
       "targetFull": "aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(lando.$server.df-*.df_complex-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(lando.$server.df-*.df_complex-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2)"
      }
     ]
    },
    {
     "title": "Disk Inodes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "target": "aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2)",
       "targetFull": "aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(lando.$server.*.df_inodes-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(lando.$server.*.df_inodes-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2)"
      }
     ]
    },
    {
     "title": "Disk - Time per operation",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "target": "exclude(aliasByNode(summarize(lando.$server.disk.disk_io_time, '$timeperiod', 'max', false), 1, 2), 'loop')"
      },
      {
       "target": "aliasByNode(summarize(scale(lando.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_io_time.io_time, 0.01), '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Operations per second",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "targets": [
      {
       "target": "exclude(aliasByNode(summarize(lando.$server.disk-*.disk_ops.read, '$timeperiod', 'max', false), 1, 2), 'loop')"
      },
      {
       "target": "aliasByNode(summarize(lando.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_ops.write, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Pending I/O requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(summarize(lando.$server.disk-*.pending_operations, '$timeperiod', 'max', false), 1, 2)"
      }
     ]
    },
    {
     "title": "Disk - Merged ops",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "target": "exclude(aliasByNode(summarize(lando.$server.*.disk_merged.read, '$timeperiod', 'max', false), 1, 2, 4), 'loop')"
      },
      {
       "target": "aliasByNode(summarize(lando.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_merged.write, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Time spent doing I/O",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "target": "exclude(aliasByNode(summarize(lando.$server.disk-*.disk_time.read, '$timeperiod', 'max', false), 1, 2), 'loop')"
      },
      {
       "target": "aliasByNode(summarize(lando.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_time.write, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Traffic",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "target": "exclude(aliasByNode(scale(summarize(lando.$server.disk-*.disk_octets.read, '$timeperiod', 'max', false), 8), 1, 2), 'loop')"
      },
      {
       "target": "aliasByNode(scale(summarize(lando.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_octets.write, '$timeperiod', 'max', false), 8), 1, 2, 4)"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Traffic/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(summarize(scale(lando.$server.interface-*.if_octets.rx, 8), '$timeperiod', 'max', false), 1, 2)"
    },
    {
     "target": "aliasByNode(summarize(scale(lando.$server.interface-*.if_octets.tx, 8), '$timeperiod', 'max', false), 1, 2)"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(summarize(lando.$server.interface-*.if_packets.rx, '$timeperiod', 'max', false), 1, 2)"
    },
    {
     "target": "aliasByNode(summarize(lando.$server.interface-*.if_packets.tx, '$timeperiod', 'max', false), 1, 2)"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(summarize(lando.$server.interface-*.if_errors.rx, '$timeperiod', 'max', false), 1, 2)"
    },
    {
     "target": "aliasByNode(summarize(lando.$server.interface-*.if_errors.tx, '$timeperiod', 'max', false), 1, 2)"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "aliasByNode(summarize(lando.$server.users.users, '$timeperiod', 'min', false), 1)"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "target": "aliasByNode(summarize(lando.$server.entropy.entropy, '$timeperiod', 'min', false), 1)"
    }
   ]
  }
 ]
}